config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  
  resources :channels do
    resources :shows
  end
  get 'my_fav_show/:id', :to => 'shows#my_fav_show', as: :add_my_fav
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  has_many :shows
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :channel
  has_many :user_fav_shows
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_fav_shows
end

app/models/user_fav_show.rb
class UserFavShow < ActiveRecord::Base

  belongs_to :user
  belongs_to :show
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @channels = Channel.all.order('id desc')
    if params[:search]
      search_key = "%#{params[:search]}%"
      @channels = Channel.where("name LIKE ?", search_key)
      @shows = Show.where("name LIKE ?", search_key)
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController

  def my_fav_show
    show = Show.find params[:id]
    if show.present?
      UserFavShow.create({user_id: current_user.id, show_id: show.id})
      flash[:notice] = "Added to fav show"
    else
      flash[:alert] = "No show found"
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/index.html.erb
<div class="row">
  <h1>
    Welcome to your fav tv shows
  </h1>
  <div class="row">
    <div class="search-form">
      <%= form_tag('/',{:method => :get}) do %>
        <input type="text" name="search">
        <input type="submit" name="submit" value="Search">
      <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <% current_user_fav_shows = current_user.user_fav_shows.pluck(:show_id) %>
    <div class="row">
      <div class="show-title-head"><h1>All Channles and fav shows list</h1></div>
      <% if !@channels.blank? %>
        <% @channels.each_with_index do |channel, i| %>
          <% current_user_fav_shows = current_user.user_fav_shows.pluck(:show_id) %>
          <div class="row channel_div">
            <span>
              <p><h3>Channel Name: </h3><%= channel.name %></p>
            </span>
            <div>
              <p><h3> Shows Name:</h3> </p>
              <ul>
                <% channel.shows.each do |show| %>
                  <li>
                    <span>
                      <%= show.name %>
                    </span>
                    <span>
                      From <%= show.start_at.strftime('%H:%M %P') %> to <%= show.end_at.strftime('%H:%M %P') %>
                    </span><br><br>
                    <span>
                      <% if current_user_fav_shows.include? show.id %>
                        <span>
                          <i class="fa fa-star"></i> My Fav
                        </span>
                      <% else %>
                        <%= link_to add_my_fav_path(show.id) do %>
                          Add my fav
                        <% end %>
                      <% end %>
                    </span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if !@shows.blank? %>
      <% @shows.each_with_index do |show, i| %>
        <div class="row channel_div">
          <span>
            <p><h3>Channel Name: </h3><%= show.channel.name %></p>
          </span>
          <div>
            <p><h3> Shows Name:</h3> </p>
            <ul>
              <% show.channel.shows.each do |show| %>
                <li>
                  <span>
                    <%= show.name %>
                  </span>
                  <span>
                    From <%= show.start_at.strftime('%H:%M %P') %> to <%= show.end_at.strftime('%H:%M %P') %>
                  </span><br><br>
                  <span>
                    <% if current_user_fav_shows.include? show.id %>
                      <span>
                        <i class="fa fa-star"></i> My Fav
                      </span>
                    <% else %>
                      <%= link_to add_my_fav_path(show.id) do %>
                        Add my fav
                      <% end %>
                    <% end %>
                  </span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
  <% else %>
    <% if !@channels.blank? %>
        <% @channels.each_with_index do |channel, i| %>
          <div class="row channel_div">
            <span>
              <p><h3>Channel Name: </h3><%= channel.name %></p>
            </span>
            <div>
              <p><h3> Shows Name:</h3> </p>
              <ul>
                <% channel.shows.each do |show| %>
                  <li>
                    <span>
                      <%= show.name %>
                    </span>
                    <span>
                      From <%= show.start_at.strftime('%H:%M %P') %> to <%= show.end_at.strftime('%H:%M %P') %>
                    </span><br><br>
                    <span>
                      Add to your fav
                    </span>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavShows</title>
  <meta charset="utf-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- This is only for test purpose -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Fav Shows</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', root_path %></li>
          <% if user_signed_in? %>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>
                Sign Out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_session_path do %>
                <i class="fa fa-sign-in"></i>
                Sign In
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user-plus"></i>
                Register
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
</body>
</html>